### ISSUE TITLE
Monero version

### ISSUE THREAD

**Issue by monero-love** [UnstoppableSwap/asb-docker-compose#4]
Is there a reason the Monero version is explicitly set to monero:v0.18.1.2? and not v0.18.1.4? in asb-docker-compose.yml?

Thanks!

**Comment by binarybaron** [comment]
No, no reason in particular. Feel free to open a PR to upgrade the container.

**Comment by darkness-su** [comment]
https://github.com/UnstoppableSwap/asb-docker-compose/pull/7
